var g_resources = [
	{src: "img/ground.png"},
	{src: "img/mainChar.png"},
	{src: "img/obs_low.png"},
	// {src: "img/cerby_l1.png"},
	// {src: "img/cerby_l2.png"},
	// {src: "img/cerby_l3.png"},
	// {src: "img/cerby_l4.png"},
	// {src: "img/cerby_s1.png"},
	// {src: "img/cerby_s2.png"},
	// {src: "img/mainChar_s1.jpg"},
	// {src: "img/mainChar_s2.jpg"},
	// {src: "img/mainChar_s3.jpg"},
	// {src: "img/mainChar_s4.jpg"},
	{src: "img/enemy_bar_border.png"},
	{src: "img/hp_green.png"},
	{src: "img/sky.jpg"},
	{src: "sound/theme.mp3"},
	{src: "sound/coin.mp3"},
	{src: "img/coin/coin_1.png"},
	{src: "img/coin/coin_2.png"},
	{src: "img/coin/coin_3.png"},
	{src: "img/coin/coin_4.png"},
	{src: "img/coin/coin_5.png"},
	{src: "img/coin/coin_6.png"},
	{src: "img/coin/coin_7.png"},
	{src: "img/mainChar/main_1.png"},
	{src: "img/mainChar/main_2.png"},
	{src: "img/mainChar/main_3.png"},
	{src: "img/mainChar/main_4.png"},
	{src: "img/mainChar/main_5.png"},
	{src: "img/mainChar/main_6.png"},
	{src: "img/mainChar/main_7.png"},
	{src: "img/mainChar/main_8.png"},
	{src: "img/mainChar/main_9.png"},
	{src: "img/mainChar/main_10.png"},
	{src: "img/coin_top.png"},
	{src: "img/menu/menu_0.png"},
	{src: "img/menu/menu_1.png"},
	{src: "img/menu/selection.png"},
	{src: "img/menu/butt_easy.png"},
	{src: "img/menu/butt_med.png"},
	{src: "img/menu/butt_hard.png"}

	// {src: "img/stage1_floor.png"},
];